import { StyleSheet } from 'react-native'

const s = StyleSheet.create({
  container: {
    height: '100%',
  },
  header: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.2)',
  },
  metaHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingTop: 10,
    zIndex: 10,
  },
  metaHeaderStarContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.4)',
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 20,
  },
  metaHeaderStar: {
    width: 20,
    height: 20,
    marginRight: 5,
  },
  metaHeaderTextWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  metaHeaderText: {
    fontSize: 18,
    fontFamily: 'Ubuntu_700Bold',
    color: '#60433a',
    letterSpacing: -1,
  },
  titleContainer: {
    flexDirection: 'row',
    overflow: 'hidden',
  },
  titleLeft: {
    width: '50%',
  },
  titleRight: {
    width: '50%',
    position: 'relative',
  },
  titleText: {
    fontSize: 60,
    textAlign: 'left',
    fontFamily: 'Chewy_400Regular',
    color: 'white',
    lineHeight: 55,
    paddingLeft: 14,
    paddingTop: 30,
    paddingBottom: 10,
  },
  pig: {
    position: 'absolute',
    width: 300,
    height: 200,
    top: 5,
    left: 0,
  },
  levelGridScrollView: {
    backgroundColor: 'rgba(255,255,255,0.15)',
  },
  levelGrid: {
    flex: 1,
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: '100%',
    justifyContent: 'space-between',
    paddingHorizontal: '3%',
    paddingTop: 25,
  },
  levelButton: {
    width: '31%',
    backgroundColor: 'white',
    marginBottom: '3%',
    paddingTop: 12,
    paddingBottom: 12,
    borderRadius: 10,
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 10,
  },
  locked: {
    borderColor: '#aaa',
    shadowOpacity: 0,
    elevation: 0,
  },
  completed: {
    paddingTop: 10,
    paddingBottom: 10,
  },
  levelNumber: {
    fontSize: 35,
    fontFamily: 'Chewy_400Regular',
    color: '#60433a',
    textAlign: 'center',
    marginBottom: 3,
  },
  levelNumberLocked: {
    opacity: 0.2,
  },
  levelButtonPressed: {
    transform: [{ translateY: 5 }],
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.4,
    elevation: 5,
  },
  noStars: { opacity: 0.5 },
  categoryIcon: {
    position: 'absolute',
    top: -2,
    right: 7,
    backgroundColor: 'red',
    paddingVertical: 5,
    paddingHorizontal: 2,
    borderBottomRightRadius: 5,
    borderBottomLeftRadius: 5,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.1)',
    borderTopWidth: 0,
  },
  lockBarrier: {
    width: '100%',
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  lockBarrierOpen: {
    opacity: 0.3,
  },
  lockLine: {
    height: 3,
    backgroundColor: '#60433a',
    flex: 1,
  },
  lockText: {
    paddingHorizontal: 5,
    alignItems: 'center',
    flexDirection: 'row',
  },
  lockTextInner: {
    fontSize: 20,
    fontFamily: 'Ubuntu_700Bold',
    letterSpacing: -1,
    color: '#60433a',
    marginLeft: 1,
  },
  lockIcon: {
    marginRight: 5,
  },
  firstLaunch: {
    position: 'absolute',
    top: '50%',
    marginTop: -100,
    left: 0,
    width: '100%',
    backgroundColor: 'white',
    paddingVertical: 50,
    paddingHorizontal: 30,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 1,
    shadowRadius: 200,
    alignItems: 'flex-start',
    zIndex: 50,
    elevation: 100,
  },
  firstLaunchText: {
    fontFamily: 'Chewy_400Regular',
    fontSize: 30,
    color: '#60433a',
    textAlign: 'left',
    marginBottom: 25,
    width: '100%',
  },
  firstLaunchBtn: {
    padding: 15,
    backgroundColor: '#facc15',
    width: '100%',
    textAlign: 'center',
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  firstLaunchBtnTextWrapper: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
  },
  firstLaunchBtnText: {
    fontSize: 24,
    fontFamily: 'Ubuntu_700Bold',
    color: '#60433a',
    textAlign: 'center',
    letterSpacing: -1,
    marginLeft: 5,
  },
  iapContainer: {
    backgroundColor: 'white',
    marginHorizontal: '3%',
    marginBottom: 25,
    marginTop: 10,
    padding: 20,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 10,
  },
  iapTitle: {
    fontFamily: 'Chewy_400Regular',
    fontSize: 40,
    color: '#60433a',
    marginBottom: 10,
    paddingTop: 10,
    textAlign: 'left',
    lineHeight: 42,
  },
  iapIntro: {
    fontFamily: 'Ubuntu_400Regular',
    color: '#60433a',
    fontSize: 17,
    lineHeight: 24,
    marginBottom: 10,
  },
  iapButton: {
    marginTop: 0,
    padding: 20,
    overflow: 'hidden',
    marginLeft: -20,
    marginRight: -20,
    marginTop: 10,
  },
  iapButtonTitle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  iapButtonTitleText: {
    fontFamily: 'Chewy_400Regular',
    color: 'white',
    fontSize: 30,
  },
  iapButtonText: {
    fontFamily: 'Ubuntu_400Regular',
    fontSize: 18,
    color: 'white',
  },
  iapButtonBackground: {
    position: 'absolute',
  },
  coffeeIcon: {
    position: 'absolute',
    top: 5,
    right: 0,
  },
  boagLogoWrapper: {
    width: 80,
    height: 30,
    opacity: 0.4,
    marginBottom: 40,
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  boagLogo: {
    width: '100%',
    height: '100%',
  },
})

export { s }
