import { StyleSheet } from 'react-native'

const s = StyleSheet.create({
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 10,
  },
  headerInner: {
    paddingLeft: 13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoryLabel: {
    padding: 5,
    paddingLeft: 10,
    paddingRight: 20,
    borderWidth: 1,
    marginRight: -1,
    borderColor: 'rgba(0,0,0,0.1)',
    borderTopLeftRadius: 5,
    borderBottomLeftRadius: 5,
  },
  headerBackButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerText: {
    fontFamily: 'Ubuntu_700Bold',
    fontSize: 18,
    letterSpacing: -1,
    color: '#60433a',
  },
  mainWrapper: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    position: 'relative',
  },
  question: {
    width: '100%',
  },
  questionNumberText: {
    fontSize: 28,
    fontFamily: 'Chewy_400Regular',
    color: 'white',
    textAlign: 'left',
    marginBottom: 15,
    opacity: 1,
  },
  questionText: {
    fontSize: 28,
    fontFamily: 'Ubuntu_500Medium',
    color: '#fff',
    textAlign: 'left',
  },
  answers: {
    width: '100%',
    marginTop: 15,
  },
  answerButton: {
    padding: 10,
    backgroundColor: 'white',
    width: '100%',
    textAlign: 'center',
    borderRadius: 10,
    shadowColor: '#000',
    marginTop: 15,
    flexDirection: 'row',
    alignItems: 'center',
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.15,
    shadowRadius: 2,
    elevation: 10,
  },
  answerButtonLetter: {
    fontSize: 30,
    fontFamily: 'Chewy_400Regular',
    width: 50,
    height: 50,
    borderRadius: 7,
    color: '#60433a',
    textAlign: 'center',
    overflow: 'hidden',
    marginRight: 15,
    paddingTop: 6,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.1)',
  },
  answerButtonText: {
    fontSize: 24,
    fontFamily: 'Ubuntu_700Bold',
    color: '#60433a',
    textAlign: 'left',
    letterSpacing: -1.5,
    flex: 1,
    paddingRight: 10,
    paddingVertical: 5,
  },
  answerButtonPressed: {
    transform: [{ translateY: 5 }],
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.4,
    elevation: 5,
  },
  nextButton: {
    shadowOpacity: 0,
    elevation: 0,
    width: '90%',
    paddingLeft: 15,
  },
  nextButtonText: {
    paddingRight: 0,
  },
  questionResult: {
    position: 'absolute',
    top: '50%',
    marginTop: -100,
    left: 0,
    width: '100%',
    backgroundColor: 'white',
    paddingVertical: 50,
    paddingHorizontal: 30,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 1,
    shadowRadius: 200,
    alignItems: 'center',
    elevation: 100,
  },
  questionResultText: {
    fontFamily: 'Chewy_400Regular',
    fontSize: 40,
    color: '#60433a',
    textAlign: 'center',
    marginBottom: 10,
  },
  normalPig: {
    width: 100,
    height: 80,
  },
  deadPig: {
    width: 100,
    height: 80,
    transform: [{ rotate: '180deg' }],
  },
})

export { s }
